name: 'Only call GitHub Status Page'
description: 'Greet someone and call GitHub status page'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  give-me-your-token-now:  # id of input
    description: 'Gets GitHub token!'
    required: true
outputs:
  time: # id of output
    description: 'Returns GitHub status page'
  status: # id of output
    description: 'GitHub status page result'
runs:
  using: 'node16'
  main: 'index.js'
